apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
data:
  username: <base64-encoded-username>
  password: <base64-encoded-password>
---
apiVersion: v1
kind: Secret
metadata:
  name: oauth-credentials
type: Opaque
data:
  JWT_SECRET: <base64-encoded-jwt-secret>
  GOOGLE_CLIENT_ID: <base64-encoded-google-client-id>
  GOOGLE_CLIENT_SECRET: <base64-encoded-google-client-secret>
  GOOGLE_REDIRECT_URL: <base64-encoded-google-redirect-url>
